# Welcome to Elite Feet!

You are a data scientist at Elite Feet. You just got hired to perform an experiment to test new shoe inserts that are supposed to make shoes feel 83% more comfortable!

You have found 22 ~~victims~~ participants who have agreed to try the shoe inserts for free. Now it's time to run the experiments to see if these work! You first have to divide the participants up into a treatment group (people who use the inserts) and a control group (people who don't use the inserts). Let's get going!

## Lab: Experimental Design

In this lab, you will:

- Download a dataset and place it in your working directory
- Utilize pandas to see how different sampling techniques affect your results
- Perform data cleaning on the dataset
- Think creatively on using pandas to solve real-world problems

## 00. Group

Edit the next Python cell to add information about who you're working within your lab section:

In [ ]:
partner1_name = "Chrysilla"
partner1_netid = "cfr4"
partner1_major = "Statistics&Computer Science"

partner2_name = "Prat"
partner2_netid = "psiyer2"
partner2_major = "Econometrics and Statistics"

partner3_name = "Tom"
partner3_netid = "tomt2"
partner3_major = "Finance and Statistics"

## 0. Setup

In the _beginning_ of every project, you will always need to:

1. Download the dataset and place it into **your working directory**. 
2. Import the `pandas` library (as `pd`) to use pandas functions.
3. Read the dataset into a DataFrame `df` using `pd.read_csv()`

### 0.1. This Lab's Dataset: Former Stat 107 Students!

You will use a dataset created by former Stat 107 students.  Assume they are the participants in this study!

- This dataset is in the lab_exp_design folder and it's named data.csv. So it's already where it needs to be!


### 0.1. Puzzle : Complete the Setup your Python Notebook

Use the following two cells to finish up the setup by following 3 steps above:

In [4]:
import pandas as pd

In [5]:
# Read the dataset into a DataFrame
df = pd.read_csv("data.csv")
df

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
0,Jesse,Undeclared,Freshmen,Dogs,1,9.0,KBBQ,Blue,iPhone,PC,...,McDonald's,0,5,0,1,15,10.0,1,Black,0
1,Bing,Psychology,Junior,Dogs,0,5.5,French Fries,Grey,iPhone,Mac,...,McDonald's,2,5,2,0,22,6.0,3,Brown,60
2,Jiayi,psychology,freshman,cats,0,7.0,hotpot,blue,iphone,PC,...,neither,0,1,0,0,17,7.0,2,black,63
3,Tamun,Psychology,Freshman,dogs,1,8.0,Indian Food,Seafoam green,iPhone,Mac,...,McDonalds,4,12,1,0,18,8.0,3,Brown,63
4,Gabby,Undeclared,Sophomore,Dogs,1,8.5,Ribs,Periwinkle,iPhone,Mac,...,Neither,3,12,2,0,17,10.5,1,Brown & Green,64
5,Cecilia,Agricultural Consumer Economics,Junior,Dogs,1,7.5,Brownie,White,Iphone,Mac,...,McDonald's,0,2,1,0,15,8.0,4,Black,64
6,Jasmine,MCB,Sophomore,Dogs,2,8.0,sushi,grey,iphone,PC,...,McDonalds,0,1,0,0,18,7.0,3,brown,64
7,Pavitra,Ag Consumer Econ,Junior,Dogs,0,7.5,mac and cheese,purple,iphone,mac,...,mcdonalds,5,9,2,1,16,8.0,2,brown,65
8,Brian,Chemistry,Sophomore,Dogs,1,9.5,Tacos,Gold,IPhone,PC,...,McDonalds,0,6,0,0,16,7.0,2,Brown,65
9,Kelly,Computer Scinece,super senior,Cats,0,7.0,Guacamole,Purple,iPhone,Mac,...,McDonald's,4,2,0.5,5,12,10.0,3,Hazel,65
10,Ali,Undeclared,Sophomore,Dogs,2,9.0,Sushi,Blue,iPhone,Mac,...,Burger King,0,2,0,1,15,10.0,2,Blue,66
11,Mariel,Global Studies,Freshman,Dogs,1,9.0,sushi,none,iPhone,Mac,...,Neither,4,10,1,0,17,10.0,3,Brown,67
12,April,Human Nutrition,Senior,Dogs,0,6.5,Hotpot,Blue,iPhone,PC,...,Neither,2,9,0,0,22,8.0,3,Black,67
13,Dean,Economics,Sophomore,Dogs,1,7.5,Ramen,Green,Android,PC,...,McDonald's,0,3,1,0,16,10.0,4,Brown,68
14,Hermon,MCB,senior,Dogs,1,10.0,Burrito,Red,iPhone,Mac,...,McDees,0,4,2,0,16,7.0,~4,Brown,68
15,Karle,Statistics,Old,Cats,2,8.5,Tacos,Pink,iPhone,Mac,...,Neither,3,10,20+,1,4,10.0,3,Green,70
16,Ming,Econ and Stats,Sophomore,Cats,1,10.0,KBBQ/Ramen,Blue,Android,PC,...,McDonalds,0,7,2,1,18,10.0,3-Feb,Brown,70
17,David,Kinesiology,Sophomore,Cats,2,10.0,Pizza,Purple,iPhone,Mac,...,neither,3,7,1,0,16,7.0,0,Grey,70
18,Omri,Lighting Design & Technology,Junior,Dogs,1,10.0,Pasta,Blue,iPhone,Mac,...,McDonald's,3,9,1,0,20,8.0,3,Brown,70
19,Nick,Advertising,freshman,dogs,1,10.0,Mac & Cheese,blue,iPhone,Mac,...,McDonald's,3,12,1,0,15,8.0,2,brown,72
20,Pedro,Political Science,Sophmore,Dogs,1,13.0,BBQ Ribs,grey,Iphone,Mac,...,Burger King,0,2,1,0,16,9.0,2,Brown,74
21,Wade,Computer Scinece,Old,Dogs,2,13.0,BBQ,Purple,Android,PC,...,MCDs,0,11,0,5,13,8.0,2,Brown,77

In [6]:
## == TEST CASES for Puzzle 1.1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(df) == 22), "The dataframe does not appear to have correct dataset loaded"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

## The Data

You have a file called data.csv which contains the names of participants in the order they registered to participate in the study. This file contains useful information for you like the participants' gender, age, height, shoe size, and opinion of Crocs.

Taylor Swift, a popular data scientist, has decided that average shoe size is going to be an important variable for the study, and that is what she wants you to measure first for both the treatment and control groups. Ideally, the averages for the two groups should be about the same because like we learned in lecture, we want the **two groups** to be as **alike** as possible.

## 1. The Easy Way

Taylor's coworker, Olivia, who is known for taking short cuts, says she knows how to split the participants into two groups: take the first 11 people from the list and put them into the control group, then put the rest of them in the treatment group.

### Quick tip: Pandas cheat sheet will help! Use it!

*If you don't have it, just Google **pandas cheat sheet*** or look on our class website under "Resources."

Use the pandas cheat sheet and create the treatment and control groups using Olivia's strategy.  Instead of just using one DataFrame, we will want to create two new DataFrames:

- `control`, a DataFrame that contains the control group
- `treatment`, a DataFrame that contains the treatment group

Because `control` and `treatment` are just DataFrames, they can do all the same things as `df` except by a different name.  This means you will have three DataFrames:

- `df`, contains all of your data
- `control`, contains your control group data
- `treatment`, contains your treatment group data

### 1.1. Puzzle : Create the control group

Using Olivia's strategy, create the control group DataFrame `control` by selecting a subset of the data from `df`. 

**Hint** Use the pandas cheat sheet and what we have learned in lecture to do this!

In [7]:
# Assign the people into the control group Using *Olivia's strategy*
control = df.head(11)
control

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
0,Jesse,Undeclared,Freshmen,Dogs,1,9.0,KBBQ,Blue,iPhone,PC,...,McDonald's,0,5,0,1,15,10.0,1,Black,0
1,Bing,Psychology,Junior,Dogs,0,5.5,French Fries,Grey,iPhone,Mac,...,McDonald's,2,5,2,0,22,6.0,3,Brown,60
2,Jiayi,psychology,freshman,cats,0,7.0,hotpot,blue,iphone,PC,...,neither,0,1,0,0,17,7.0,2,black,63
3,Tamun,Psychology,Freshman,dogs,1,8.0,Indian Food,Seafoam green,iPhone,Mac,...,McDonalds,4,12,1,0,18,8.0,3,Brown,63
4,Gabby,Undeclared,Sophomore,Dogs,1,8.5,Ribs,Periwinkle,iPhone,Mac,...,Neither,3,12,2,0,17,10.5,1,Brown & Green,64
5,Cecilia,Agricultural Consumer Economics,Junior,Dogs,1,7.5,Brownie,White,Iphone,Mac,...,McDonald's,0,2,1,0,15,8.0,4,Black,64
6,Jasmine,MCB,Sophomore,Dogs,2,8.0,sushi,grey,iphone,PC,...,McDonalds,0,1,0,0,18,7.0,3,brown,64
7,Pavitra,Ag Consumer Econ,Junior,Dogs,0,7.5,mac and cheese,purple,iphone,mac,...,mcdonalds,5,9,2,1,16,8.0,2,brown,65
8,Brian,Chemistry,Sophomore,Dogs,1,9.5,Tacos,Gold,IPhone,PC,...,McDonalds,0,6,0,0,16,7.0,2,Brown,65
9,Kelly,Computer Scinece,super senior,Cats,0,7.0,Guacamole,Purple,iPhone,Mac,...,McDonald's,4,2,0.5,5,12,10.0,3,Hazel,65
10,Ali,Undeclared,Sophomore,Dogs,2,9.0,Sushi,Blue,iPhone,Mac,...,Burger King,0,2,0,1,15,10.0,2,Blue,66

In [8]:
## == TEST CASES for Puzzle 1.1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(control) == 11), "The control group does not appear to have correctly chosen"
assert((control["Name"] == df["Name"][10]).sum() == 1), "The control group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

### 1.2. Puzzle :  Create the treatment group

Using Olivia's strategy, create the treatment group DataFrame `treatment`:

In [9]:
# Assign the people into the treatment group Using *Olivia's strategy*
treatment = df.tail(11)
treatment

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
11,Mariel,Global Studies,Freshman,Dogs,1,9.0,sushi,none,iPhone,Mac,...,Neither,4,10,1,0,17,10.0,3,Brown,67
12,April,Human Nutrition,Senior,Dogs,0,6.5,Hotpot,Blue,iPhone,PC,...,Neither,2,9,0,0,22,8.0,3,Black,67
13,Dean,Economics,Sophomore,Dogs,1,7.5,Ramen,Green,Android,PC,...,McDonald's,0,3,1,0,16,10.0,4,Brown,68
14,Hermon,MCB,senior,Dogs,1,10.0,Burrito,Red,iPhone,Mac,...,McDees,0,4,2,0,16,7.0,~4,Brown,68
15,Karle,Statistics,Old,Cats,2,8.5,Tacos,Pink,iPhone,Mac,...,Neither,3,10,20+,1,4,10.0,3,Green,70
16,Ming,Econ and Stats,Sophomore,Cats,1,10.0,KBBQ/Ramen,Blue,Android,PC,...,McDonalds,0,7,2,1,18,10.0,3-Feb,Brown,70
17,David,Kinesiology,Sophomore,Cats,2,10.0,Pizza,Purple,iPhone,Mac,...,neither,3,7,1,0,16,7.0,0,Grey,70
18,Omri,Lighting Design & Technology,Junior,Dogs,1,10.0,Pasta,Blue,iPhone,Mac,...,McDonald's,3,9,1,0,20,8.0,3,Brown,70
19,Nick,Advertising,freshman,dogs,1,10.0,Mac & Cheese,blue,iPhone,Mac,...,McDonald's,3,12,1,0,15,8.0,2,brown,72
20,Pedro,Political Science,Sophmore,Dogs,1,13.0,BBQ Ribs,grey,Iphone,Mac,...,Burger King,0,2,1,0,16,9.0,2,Brown,74
21,Wade,Computer Scinece,Old,Dogs,2,13.0,BBQ,Purple,Android,PC,...,MCDs,0,11,0,5,13,8.0,2,Brown,77

In [10]:
### == TEST CASES for Puzzle 1.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(treatment) == 11), "The treatment group does not appear to have correctly chosen"
assert((treatment["Name"] == df["Name"][11]).sum() == 1), "The treatment group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

## 1.3. Find the mean (average) shoe size

On the back of the cheat sheet, you will find pandas can summarize data:

![image.png](pandas-summarize-data.png)

### Using the summary functions on a column:

We can use any of the summary functions, `sum()`, `count()`, `median()`, `quantile(...)`, `apply(...)`, `min()`, `max()`, `mean()`, `var()`, and `std()` to any column by applying it to a column in the DataFrame.

The syntax to get one column from a DataFrame is to **index into the column**.  For example:

```
df['Credit Hours'].max()
```

...will return the max number of credit hours.

### 1.3. Puzzle: Find the mean (average) shoe size

Find and `print` the average shoe size of the control *and* treatment groups:

In [16]:
# Assign the average shoe size of control group
control_shoe_mean = control['Shoe Size?'].mean()
# Print the control_shoe_mean
print(control_shoe_mean)

# Assign the average shoe size of treatment group
treatment_shoe_mean = treatment['Shoe Size?'].mean()
# Print the treatment_shoe_mean
print(treatment_shoe_mean)

7.863636363636363
9.772727272727273

In [15]:
### == TEST CASES for Puzzle 1.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(control_shoe_mean == control['Shoe Size?'].mean()), "The average shoe size of your control group does not appear to seem correct. Make sure you are taking mean of the correct variable."
assert(treatment_shoe_mean == treatment['Shoe Size?'].mean()), "The average shoe size of your treatment group does not appear to seem correct. Make sure you are taking mean of the correct variable."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

## 1.4. Individual Reflection:

Do you think this is the best way to choose who is in the treatment group and the control group? Why or why not? Type your short answer in the cell below.

No because it is not randomized. They simply choose the first 11 responses.

## 2. The Random Way

Taylor's coworker, Ed, took a stats course in college and stayed awake through at least 50% of the lectures. He remembers that you have to use randomization to determine who goes in each group in order to make the groups as *alike* as possible. He suggests that you randomly pick 11 people to be in the treatment group and the other 11 should go in the control group.

### 2.1. Creating the control and the treatment groups using randomization

Execute Ed's strategy for dividing up the participants to create a `control` and a `treatment` group.


**Hint:** This might help to randomize your whole dataset first: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sample.html

**Hint 2:** If the frac=0.5 parameter randomly samples 50% of the data with replacement, how can we use this to randomize the entire dataset?

*Make sure to use a different cell for `control` and `treatment`.*

In [22]:
# Assign the 11 people into the control group Using *randomization*
random_set = df.sample(frac = 1)
control_random = random_set.head(11)
control_random

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
3,Tamun,Psychology,Freshman,dogs,1,8.0,Indian Food,Seafoam green,iPhone,Mac,...,McDonalds,4,12,1,0,18,8.0,3,Brown,63
6,Jasmine,MCB,Sophomore,Dogs,2,8.0,sushi,grey,iphone,PC,...,McDonalds,0,1,0,0,18,7.0,3,brown,64
11,Mariel,Global Studies,Freshman,Dogs,1,9.0,sushi,none,iPhone,Mac,...,Neither,4,10,1,0,17,10.0,3,Brown,67
1,Bing,Psychology,Junior,Dogs,0,5.5,French Fries,Grey,iPhone,Mac,...,McDonald's,2,5,2,0,22,6.0,3,Brown,60
4,Gabby,Undeclared,Sophomore,Dogs,1,8.5,Ribs,Periwinkle,iPhone,Mac,...,Neither,3,12,2,0,17,10.5,1,Brown & Green,64
7,Pavitra,Ag Consumer Econ,Junior,Dogs,0,7.5,mac and cheese,purple,iphone,mac,...,mcdonalds,5,9,2,1,16,8.0,2,brown,65
14,Hermon,MCB,senior,Dogs,1,10.0,Burrito,Red,iPhone,Mac,...,McDees,0,4,2,0,16,7.0,~4,Brown,68
0,Jesse,Undeclared,Freshmen,Dogs,1,9.0,KBBQ,Blue,iPhone,PC,...,McDonald's,0,5,0,1,15,10.0,1,Black,0
17,David,Kinesiology,Sophomore,Cats,2,10.0,Pizza,Purple,iPhone,Mac,...,neither,3,7,1,0,16,7.0,0,Grey,70
5,Cecilia,Agricultural Consumer Economics,Junior,Dogs,1,7.5,Brownie,White,Iphone,Mac,...,McDonald's,0,2,1,0,15,8.0,4,Black,64
10,Ali,Undeclared,Sophomore,Dogs,2,9.0,Sushi,Blue,iPhone,Mac,...,Burger King,0,2,0,1,15,10.0,2,Blue,66

In [23]:
### == TEST CASES for Puzzle 2.1. ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(control_random) == 11), "The control group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

In [25]:
# Assign the rest of people into the control group Using *randomization*
treatment_random = random_set.tail(11)
treatment_random

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
13,Dean,Economics,Sophomore,Dogs,1,7.5,Ramen,Green,Android,PC,...,McDonald's,0,3,1,0,16,10.0,4,Brown,68
8,Brian,Chemistry,Sophomore,Dogs,1,9.5,Tacos,Gold,IPhone,PC,...,McDonalds,0,6,0,0,16,7.0,2,Brown,65
18,Omri,Lighting Design & Technology,Junior,Dogs,1,10.0,Pasta,Blue,iPhone,Mac,...,McDonald's,3,9,1,0,20,8.0,3,Brown,70
12,April,Human Nutrition,Senior,Dogs,0,6.5,Hotpot,Blue,iPhone,PC,...,Neither,2,9,0,0,22,8.0,3,Black,67
19,Nick,Advertising,freshman,dogs,1,10.0,Mac & Cheese,blue,iPhone,Mac,...,McDonald's,3,12,1,0,15,8.0,2,brown,72
15,Karle,Statistics,Old,Cats,2,8.5,Tacos,Pink,iPhone,Mac,...,Neither,3,10,20+,1,4,10.0,3,Green,70
9,Kelly,Computer Scinece,super senior,Cats,0,7.0,Guacamole,Purple,iPhone,Mac,...,McDonald's,4,2,0.5,5,12,10.0,3,Hazel,65
21,Wade,Computer Scinece,Old,Dogs,2,13.0,BBQ,Purple,Android,PC,...,MCDs,0,11,0,5,13,8.0,2,Brown,77
20,Pedro,Political Science,Sophmore,Dogs,1,13.0,BBQ Ribs,grey,Iphone,Mac,...,Burger King,0,2,1,0,16,9.0,2,Brown,74
16,Ming,Econ and Stats,Sophomore,Cats,1,10.0,KBBQ/Ramen,Blue,Android,PC,...,McDonalds,0,7,2,1,18,10.0,3-Feb,Brown,70
2,Jiayi,psychology,freshman,cats,0,7.0,hotpot,blue,iphone,PC,...,neither,0,1,0,0,17,7.0,2,black,63

In [26]:
### == TEST CASES for Puzzle 2.1. ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(treatment_random) == 11), "The control group does not appear to have correctly chosen"
for x in treatment_random["Name"]:
    a = (len(control_random[control_random['Name'].str.contains(str(x))])==0)
assert(a), "The treatment group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

### SANITY CHECK !!!

- **MAKE SURE** that each group has unique people and that no single person is in both groups.

### 2.2. Puzzle : Finding mean shoe sizes
Now again try to find and `print` the average shoe size of the **randomized** control *and* **randomized** treatment groups.

In [32]:
# Assign the average shoe size of control group
control_random_shoe_mean = control_random['Shoe Size?'].mean()
# Print the control_shoe_mean
print(control_random_shoe_mean)

# Assign the average shoe size of treatment group
treatment_random_shoe_mean = treatment_random['Shoe Size?'].mean()
# Print the treatment_shoe_mean
print(treatment_random_shoe_mean)

8.363636363636363
9.272727272727273

In [33]:
### == TEST CASES for Puzzle 2.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(control_random_shoe_mean == control_random['Shoe Size?'].mean()), "The average shoe size of your control group does not appear to seem correct. Make sure you are taking mean of the correct variable."
assert(treatment_random_shoe_mean == treatment_random['Shoe Size?'].mean()), "The average shoe size of your treatment group does not appear to seem correct. Make sure you are taking mean of the correct variable."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

### 2.3. Individual Reflection:
Do you think this is the best way to decide who is in the treatment and control groups? Why or why not? Type your short answer below.

No because there is the possibility of counfounding variables. It will be better to stratify the results based on a variable such as year.

## 3. Blocking!

Taylor's BFF, Karle, took many stats courses in college and is confident that, with such a small sample, you need to block the participants before randomly assigning them to the groups to ensure the groups are as *alike* as possible. With small samples, accidental differences can occur even if we randomly divide participants!

### 3.1: Group Discussion

Run `df.columns` to view all the columns in our dataset. What variable do you think you should block on?  In other words, what variable do you think will influence the response the most? Identify some possible variables and discuss with your group how they could affect the conclusion of the experiment.

In [34]:
df.columns

Index(['Name', 'Major?', 'Year?', 'Cats or Dogs', 'Siblings?', 'Shoe Size?',
       'Fav Food', 'Fav. Color', 'Phone?', 'Mac or PC?', 'Travel ',
       'Fav Subject', 'Crocs?', 'Musical Artist', 'Pancakes or waffles',
       'Fav Animal', 'Fav Car', 'Do You Cook?', 'Marvel or DC?', 'Fav Movie',
       'Airpods', 'Instrument', 'Fav Store IRL', 'Pepsi or Coke', 'The Dress',
       'Fav Restaurant', 'Least Fav Subject', 'McDonald's or Burger King',
       'Gym Per Week', 'Birth Month', 'Stat at UIUC', 'Programming at UIUC',
       'Credit Hours?', 'Ideal Sleep Hours', 'Eat Out Per Week', 'Eye Color',
       'Height / ft + in'],
      dtype='object')

### 3.2. Puzzle: Creating `block1` and `block2`

Blocking is just dividing subjects into groups based on a certain variable. We block before randomized controlled experiments. You can block based on multiple variables, but today we just want you to pick one. This is subjective, but we are going to use Height (measured in feet + inches) in this lab. This variable is called: Height / ft + in

In our dataset, we have two blocks (or groups) that we can name `block1` and `block2`. Create DataFrames `block1` and `block2` that contain data based on our blocking condition. Remember for this lab, we will use **Height / ft + in** as the blocking condition. Use Python to create `block1` that contains the students who have a *Height / ft + in* greater than 65. And create `block2` that contains students who have a *Height / ft + in* less than or equal to 65.


*You should use a different cell for `block1` and `block2`.*

In [42]:
# Create the block1 based on blocking condition
block1 = df[df['Height / ft + in'] > 65]
block1

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
10,Ali,Undeclared,Sophomore,Dogs,2,9.0,Sushi,Blue,iPhone,Mac,...,Burger King,0,2,0,1,15,10.0,2,Blue,66
11,Mariel,Global Studies,Freshman,Dogs,1,9.0,sushi,none,iPhone,Mac,...,Neither,4,10,1,0,17,10.0,3,Brown,67
12,April,Human Nutrition,Senior,Dogs,0,6.5,Hotpot,Blue,iPhone,PC,...,Neither,2,9,0,0,22,8.0,3,Black,67
13,Dean,Economics,Sophomore,Dogs,1,7.5,Ramen,Green,Android,PC,...,McDonald's,0,3,1,0,16,10.0,4,Brown,68
14,Hermon,MCB,senior,Dogs,1,10.0,Burrito,Red,iPhone,Mac,...,McDees,0,4,2,0,16,7.0,~4,Brown,68
15,Karle,Statistics,Old,Cats,2,8.5,Tacos,Pink,iPhone,Mac,...,Neither,3,10,20+,1,4,10.0,3,Green,70
16,Ming,Econ and Stats,Sophomore,Cats,1,10.0,KBBQ/Ramen,Blue,Android,PC,...,McDonalds,0,7,2,1,18,10.0,3-Feb,Brown,70
17,David,Kinesiology,Sophomore,Cats,2,10.0,Pizza,Purple,iPhone,Mac,...,neither,3,7,1,0,16,7.0,0,Grey,70
18,Omri,Lighting Design & Technology,Junior,Dogs,1,10.0,Pasta,Blue,iPhone,Mac,...,McDonald's,3,9,1,0,20,8.0,3,Brown,70
19,Nick,Advertising,freshman,dogs,1,10.0,Mac & Cheese,blue,iPhone,Mac,...,McDonald's,3,12,1,0,15,8.0,2,brown,72
20,Pedro,Political Science,Sophmore,Dogs,1,13.0,BBQ Ribs,grey,Iphone,Mac,...,Burger King,0,2,1,0,16,9.0,2,Brown,74
21,Wade,Computer Scinece,Old,Dogs,2,13.0,BBQ,Purple,Android,PC,...,MCDs,0,11,0,5,13,8.0,2,Brown,77

In [43]:
## == TEST CASES for Puzzle 3.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(block1) == 12), "The block1 group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

In [45]:
block2 = df[df['Height / ft + in'] <= 65]
block2

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
0,Jesse,Undeclared,Freshmen,Dogs,1,9.0,KBBQ,Blue,iPhone,PC,...,McDonald's,0,5,0,1,15,10.0,1,Black,0
1,Bing,Psychology,Junior,Dogs,0,5.5,French Fries,Grey,iPhone,Mac,...,McDonald's,2,5,2,0,22,6.0,3,Brown,60
2,Jiayi,psychology,freshman,cats,0,7.0,hotpot,blue,iphone,PC,...,neither,0,1,0,0,17,7.0,2,black,63
3,Tamun,Psychology,Freshman,dogs,1,8.0,Indian Food,Seafoam green,iPhone,Mac,...,McDonalds,4,12,1,0,18,8.0,3,Brown,63
4,Gabby,Undeclared,Sophomore,Dogs,1,8.5,Ribs,Periwinkle,iPhone,Mac,...,Neither,3,12,2,0,17,10.5,1,Brown & Green,64
5,Cecilia,Agricultural Consumer Economics,Junior,Dogs,1,7.5,Brownie,White,Iphone,Mac,...,McDonald's,0,2,1,0,15,8.0,4,Black,64
6,Jasmine,MCB,Sophomore,Dogs,2,8.0,sushi,grey,iphone,PC,...,McDonalds,0,1,0,0,18,7.0,3,brown,64
7,Pavitra,Ag Consumer Econ,Junior,Dogs,0,7.5,mac and cheese,purple,iphone,mac,...,mcdonalds,5,9,2,1,16,8.0,2,brown,65
8,Brian,Chemistry,Sophomore,Dogs,1,9.5,Tacos,Gold,IPhone,PC,...,McDonalds,0,6,0,0,16,7.0,2,Brown,65
9,Kelly,Computer Scinece,super senior,Cats,0,7.0,Guacamole,Purple,iPhone,Mac,...,McDonald's,4,2,0.5,5,12,10.0,3,Hazel,65

In [46]:
## == TEST CASES for Puzzle 3.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(len(block2) == 10), "The block2 group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

### 3.3. Puzzle:  Creating the final treatment and control groups

Execute Karle's strategy for dividing up the participants to create a `control_block` group and a `treatment_block` group such that half of the students in each block will be in the treatment group and half will be in the control group. Dont forget to **randomize**! In other words, randomly assign half of the subjects from block1 to treatment and half to control. Do the same thing with block2.

**HINT**:  Will you need to gather data from two places?  Is there something on the cheat sheet that lets you combine two datasets? 
https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

*You should use a different cell for `control_block` and `treatment_block`.*

You have several cells to work in if you need them. The only requirement is that your final `control_block` and `treatment_block` groups must be randomly selected and be stored in the variable `control_block` and `treatment_block` .

**HINT**: The tilde operator negates the Boolean values in the DataFrame. E.g. try running `~pd.Series([True,False])`

In [49]:
# You can use this cell to work on creating the control group from the blocks.
randBlock1 = block1.sample(frac=1)
randBlock2 = block2.sample(frac=1)

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
19,Nick,Advertising,freshman,dogs,1,10.0,Mac & Cheese,blue,iPhone,Mac,...,McDonald's,3,12,1,0,15,8.0,2,brown,72
10,Ali,Undeclared,Sophomore,Dogs,2,9.0,Sushi,Blue,iPhone,Mac,...,Burger King,0,2,0,1,15,10.0,2,Blue,66
16,Ming,Econ and Stats,Sophomore,Cats,1,10.0,KBBQ/Ramen,Blue,Android,PC,...,McDonalds,0,7,2,1,18,10.0,3-Feb,Brown,70
11,Mariel,Global Studies,Freshman,Dogs,1,9.0,sushi,none,iPhone,Mac,...,Neither,4,10,1,0,17,10.0,3,Brown,67
17,David,Kinesiology,Sophomore,Cats,2,10.0,Pizza,Purple,iPhone,Mac,...,neither,3,7,1,0,16,7.0,0,Grey,70
13,Dean,Economics,Sophomore,Dogs,1,7.5,Ramen,Green,Android,PC,...,McDonald's,0,3,1,0,16,10.0,4,Brown,68
6,Jasmine,MCB,Sophomore,Dogs,2,8.0,sushi,grey,iphone,PC,...,McDonalds,0,1,0,0,18,7.0,3,brown,64
1,Bing,Psychology,Junior,Dogs,0,5.5,French Fries,Grey,iPhone,Mac,...,McDonald's,2,5,2,0,22,6.0,3,Brown,60
8,Brian,Chemistry,Sophomore,Dogs,1,9.5,Tacos,Gold,IPhone,PC,...,McDonalds,0,6,0,0,16,7.0,2,Brown,65
2,Jiayi,psychology,freshman,cats,0,7.0,hotpot,blue,iphone,PC,...,neither,0,1,0,0,17,7.0,2,black,63
7,Pavitra,Ag Consumer Econ,Junior,Dogs,0,7.5,mac and cheese,purple,iphone,mac,...,mcdonalds,5,9,2,1,16,8.0,2,brown,65

In [50]:
# Make sure your final answer is in `control_block`:
control_block = pd.concat([randBlock1.head(6), randBlock2.head(5)])

In [51]:
### == TEST CASES for Puzzle 3.3. ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(control_block) == 11), "The control group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

In [56]:
# This is the code for creating the treatment group from the blocks. It's given to you since we haven't learned how to do this yet!
treatment_block=df.iloc[~df.index.isin(control_block.index)]

In [57]:
# Make sure your final answer is in `treatment_block`. If you ran the previous cell, this is ensures your final answer is in `treatment_block`.
treatment_block

,Name,Major?,Year?,Cats or Dogs,Siblings?,Shoe Size?,Fav Food,Fav. Color,Phone?,Mac or PC?,...,McDonald's or Burger King,Gym Per Week,Birth Month,Stat at UIUC,Programming at UIUC,Credit Hours?,Ideal Sleep Hours,Eat Out Per Week,Eye Color,Height / ft + in
0,Jesse,Undeclared,Freshmen,Dogs,1,9.0,KBBQ,Blue,iPhone,PC,...,McDonald's,0,5,0,1,15,10.0,1,Black,0
3,Tamun,Psychology,Freshman,dogs,1,8.0,Indian Food,Seafoam green,iPhone,Mac,...,McDonalds,4,12,1,0,18,8.0,3,Brown,63
4,Gabby,Undeclared,Sophomore,Dogs,1,8.5,Ribs,Periwinkle,iPhone,Mac,...,Neither,3,12,2,0,17,10.5,1,Brown & Green,64
5,Cecilia,Agricultural Consumer Economics,Junior,Dogs,1,7.5,Brownie,White,Iphone,Mac,...,McDonald's,0,2,1,0,15,8.0,4,Black,64
9,Kelly,Computer Scinece,super senior,Cats,0,7.0,Guacamole,Purple,iPhone,Mac,...,McDonald's,4,2,0.5,5,12,10.0,3,Hazel,65
12,April,Human Nutrition,Senior,Dogs,0,6.5,Hotpot,Blue,iPhone,PC,...,Neither,2,9,0,0,22,8.0,3,Black,67
14,Hermon,MCB,senior,Dogs,1,10.0,Burrito,Red,iPhone,Mac,...,McDees,0,4,2,0,16,7.0,~4,Brown,68
15,Karle,Statistics,Old,Cats,2,8.5,Tacos,Pink,iPhone,Mac,...,Neither,3,10,20+,1,4,10.0,3,Green,70
18,Omri,Lighting Design & Technology,Junior,Dogs,1,10.0,Pasta,Blue,iPhone,Mac,...,McDonald's,3,9,1,0,20,8.0,3,Brown,70
20,Pedro,Political Science,Sophmore,Dogs,1,13.0,BBQ Ribs,grey,Iphone,Mac,...,Burger King,0,2,1,0,16,9.0,2,Brown,74
21,Wade,Computer Scinece,Old,Dogs,2,13.0,BBQ,Purple,Android,PC,...,MCDs,0,11,0,5,13,8.0,2,Brown,77

In [58]:
### == TEST CASES for Puzzle 3.3. ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(treatment_block) == 11), "The control group does not appear to have correctly chosen."
for x in treatment_block["Name"]:
    a = (len(control_block[control_block['Name'].str.contains(str(x))])==0)
assert(a), "The treatment group does not appear to have correctly chosen"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

### 3.4. Puzzle: Finding mean shoe sizes
After creating the treatment and control groups using blocking and randomization, let's find the average shoe size of the control *and* treatment groups again. 

Find and `print` the average shoe size of the control *and* treatment groups:

In [61]:
# Create the average shoe size of control group
control_shoe_mean = control_block['Shoe Size?'].mean()
# Print the control_shoe_mean
print(control_shoe_mean)

# Create the average shoe size of treatment group
treatment_shoe_mean = treatment_block['Shoe Size?'].mean()
# Print the treatment_shoe_mean
print(treatment_shoe_mean)

8.454545454545455
9.181818181818182

In [62]:
### == TEST CASES for Puzzle 3.4 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(control_shoe_mean == control_block['Shoe Size?'].mean()), "The average shoe size of your control group does not appear to seem correct. Make sure you are taking mean of the correct variable."
assert(treatment_shoe_mean == treatment_block['Shoe Size?'].mean()), "The average shoe size of your treatment group does not appear to seem correct. Make sure you are taking mean of the correct variable."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print()

🎉 All tests passed! 🎉

## 3.5 Individual Reflection:

- Do you think this is a good way to choose the treatment and control groups? Why or why not?

- Did the three different strategies affect the average shoe size of the two groups? If so, how?

Yes! It is randomized AND stratified on height to avoid the confounder. 
The strategies do affect average shoe size slightly. The mean shoe size seemed to get a bit closer together when we randomized/blocked.

## 3.6 Group Discussion:

This lab was an example of a controlled experiment, specifically a randomized controlled experiment with blocking. Suppose that it was an observational study instead (i.e. subjects themselves choose whether they try the new shoe inserts or not). Discuss how this would change your approach to analyzing the data at the end of the study. What are the problems with observational studies? Are there any pros to doing an observational study in this case? Discuss this with your group :)

ANS: If it was an observational study, we wouldn't be able to make the treatment/control groups alike. Therefore, we would not be able to account for confounding variables. We would have to stratify the results afterwards.

# Finale!

You're almost done -- congratulations!

You need to do two more things:

1. Save your work.  To do this, create a **notebook checkpoint** by using the menu within the notebook to go **File -> Save and Checkpoint**

2. After you have saved and checkpointed, exit this notebook and return to the Data Science Discovery page on how to use git to turn this notebook into the course!